<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>DiskLit.ico</ApplicationIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <AssemblyName>DiskLit</AssemblyName>
    <RootNamespace>DiskLit</RootNamespace>
    <InvariantGlobalization>false</InvariantGlobalization>
    <DebugType>embedded</DebugType>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
  </PropertyGroup>

  <PropertyGroup>
    <Product>DiskLit</Product>
    <Version>1.2.0</Version>
    <Authors>@romolocraft</Authors>
    <Description>Analisador de espaço em disco leve para Windows, somente leitura.</Description>
    <Copyright>Copyright (c) 2026 @romolocraft</Copyright>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="DiskLit.ico" LogicalName="DiskLit.DiskLit.ico" />
    <EmbeddedResource Include="disklit_icon.png" LogicalName="DiskLit.disklit_icon.png" />
  </ItemGroup>
</Project>
