using System.Diagnostics;
using System.Globalization;

namespace DiskLit;

internal enum Language
{
    English,
    Portuguese,
    Spanish,
    Russian
}

internal enum UiText
{
    AppTitle,
    Headline,
    Intro,
    Analyze,
    Stop,
    FilterPlaceholder,
    AllFolders,
    ColumnName,
    ColumnSize,
    ColumnLocation,
    ColumnModified,
    OpenLocation,
    CopyPath,
    Ready,
    ScanningHint,
    ScanStopped,
    ScanFailedPrefix,
    SolidState,
    Sequential,
    RootFolder,
    CouldNotOpenTitle,
    CouldNotCopyTitle,
    ProgressFormat,
    SummaryFormat,
    DoneFormat,
    DriveFormat,
    UnknownDate,
    ThemeSystem,
    ThemeLight,
    ThemeDark,
    NavFiles,
    NavActive,
    NavCleanup,
    SystemFileTitle,
    SystemFileWarning,
    SystemFileGeneric,
    SystemFileHiberfil,
    SystemFilePagefile,
    SystemFileSwapfile,
    SystemFileMemoryDump,
    SystemFileDumpStack,
    SystemFileWindowsOld,
    SystemFileWinSxS,
    SystemFileSystemVolume,
    SystemFileRecycleBin,
    SystemFileInstaller,
    SystemFileRestore,
    ActiveHint,
    ActiveRefresh,
    ColumnProcess,
    ColumnPid,
    ColumnCpu,
    ColumnMemory,
    ColumnProcessPath,
    ActiveSummaryFormat,
    ActiveUnavailable,
    CleanupHint,
    CleanupScanButton,
    CleanupRunButton,
    CleanupScanning,
    CleanupFoundFormat,
    CleanupNothing,
    CleanupColumnTarget,
    CleanupColumnItems,
    CleanupColumnSize,
    CleanupColumnLocation,
    CleanupConfirmTitle,
    CleanupConfirmFormat,
    CleanupDoneFormat,
    CleanupRecycleNote,
    CleanupNotDeep,
    TargetUserTemp,
    TargetWindowsTemp,
    TargetThumbnails,
    TargetCrashDumps,
    TargetBrowserCache,
    CategoryVideo,
    CategoryImages,
    CategoryAudio,
    CategoryArchives,
    CategoryCode,
    CategoryDocuments,
    CategorySystem,
    CategoryOther,
    SectionDrives,
    SectionFileTypes,
    StatsFormat,
    SpeedFormat,
    UsageFormat,
    DoNotDeleteHeadline,
    GroupApps,
    GroupBackground,
    CleanupExpandHint,
    CleanupSelectedFormat,
    MoveToRecycleBin,
    RecycleConfirmTitle,
    RecycleConfirmFormat,
    RecycleSystemWarning,
    RecycleFailed,
    SearchProcess,
    SearchKeywords,
    ColumnOrigin,
    OriginWindows,
    OptionsTitle,
    OptionsLanguage,
    OptionsTheme,
    OptionsSearch,
    OptionsClose,
    LanguageAuto,
    ThemeOptionSystem,
    ThemeOptionLight,
    ThemeOptionDark,
    SectionFolders,
    TargetOrphanedApps,
    TargetKnownCache,
    CleanupCancelledBusy
}

internal static class Strings
{
    static string[] table = Table(Language.English);

    public static Language Current { get; private set; } = Language.English;

    static Strings()
    {
        var expected = Enum.GetValues<UiText>().Length;
        foreach (var language in Enum.GetValues<Language>())
            Debug.Assert(Table(language).Length == expected, $"{language} table has wrong length");
    }

    public static string Get(UiText id) => table[(int)id];

    public static string Format(UiText id, params object[] values) =>
        string.Format(CultureInfo.CurrentCulture, table[(int)id], values);

    public static void UseSystemLanguage() => Use(DetectSystemLanguage());

    public static void Use(Language language)
    {
        Current = language;
        table = Table(language);
    }

    public static Language DetectSystemLanguage() =>
        CultureInfo.CurrentUICulture.TwoLetterISOLanguageName switch
        {
            "pt" => Language.Portuguese,
            "es" => Language.Spanish,
            "ru" => Language.Russian,
            _ => Language.English
        };

    static string[] Table(Language language) => language switch
    {
        Language.Portuguese =>
        [
            "DiskLit — Analisador de espaço em disco",
            "Descubra o que está ocupando seu disco",
            "Selecione um disco. A análise apenas lê os arquivos e não apaga nada.",
            "Analisar",
            "Parar",
            "Filtrar entre os maiores arquivos...",
            "Todas as pastas",
            "Nome",
            "Tamanho",
            "Localização",
            "Modificado",
            "Abrir localização",
            "Copiar caminho",
            "Pronto",
            "Analisando em segundo plano; você pode parar a qualquer momento.",
            "Análise interrompida.",
            "Não foi possível concluir: ",
            "SSD/NVMe",
            "modo sequencial",
            "(raiz)",
            "Não foi possível abrir",
            "Não foi possível copiar",
            "{0} arquivos • {1} lidos • {2} inacessíveis • {3}",
            "{0} arquivos • {1} • {2} • {3} • {4} inacessíveis",
            "Concluído. Exibindo os {0} maiores arquivos; o filtro busca apenas entre eles. Clique duas vezes para abrir a localização.",
            "{0}  {1}  •  {2} de {3}",
            "—",
            "Tema: sistema",
            "Tema: claro",
            "Tema: escuro",
            "Arquivos",
            "Ativos",
            "Limpeza",
            "Arquivo do sistema Windows",
            "Não apague manualmente. O Windows recria o arquivo, e removê-lo à mão pode deixar o sistema instável ou impedir a inicialização.",
            "Este item pertence ao Windows e é gerenciado pelo próprio sistema.",
            "Guarda o conteúdo da memória RAM quando o PC hiberna, por isso ocupa aproximadamente o tamanho da memória instalada. A Inicialização Rápida também usa esse arquivo. Para liberar o espaço, desative a hibernação com \"powercfg /h off\" num prompt como administrador.",
            "É a memória virtual. O Windows move para cá as páginas de memória menos usadas quando a RAM enche, então o tamanho acompanha sua RAM e sua carga de trabalho. Ajuste em Propriedades do Sistema > Avançado > Desempenho > Memória virtual.",
            "Memória virtual reservada para aplicativos da Microsoft Store, gerenciada junto com o arquivo de paginação.",
            "Retrato da memória gravado depois de uma tela azul, mantido para diagnóstico. Pode chegar ao tamanho da sua RAM. Remova pela Limpeza de Disco, na opção de despejos de memória de erro do sistema.",
            "Pequeno registro que o Windows grava durante o desligamento e no tratamento de falhas.",
            "É a instalação anterior do Windows, mantida para permitir voltar atrás depois de uma atualização. O próprio Windows a remove após cerca de dez dias. Se precisar antes disso, use o Sensor de Armazenamento ou a Limpeza de Disco.",
            "É o armazenamento de componentes, com todas as versões de arquivos que o Windows precisa para atualizar e reparar. O espaço real é muito menor do que aparenta, porque a maioria das entradas são hard links para arquivos que já existem em outro lugar.",
            "Guarda pontos de restauração, dados de indexação e metadados do volume. Controle o tamanho pela Proteção do Sistema.",
            "São os arquivos que você excluiu, ainda recuperáveis até esvaziar a Lixeira.",
            "Guarda dados de instalação que o Windows usa para reparar, atualizar e desinstalar programas. Apagar quebra essas operações e não há como recriar.",
            "Contém pontos de restauração do sistema. Ajuste o espaço reservado em Proteção do Sistema, em vez de apagar os arquivos.",
            "Visão ao vivo do que está em execução. Somente leitura: o DiskLit não encerra processos.",
            "Atualizar",
            "Processo",
            "PID",
            "CPU",
            "Memória",
            "Executável",
            "{0} processos • {1} de memória em uso",
            "Não foi possível ler a lista de processos.",
            "Caches conhecidos e possíveis resíduos. Revise o conteúdo: candidatos profundos ficam desmarcados.",
            "Procurar",
            "Mover para a Lixeira",
            "Procurando...",
            "{0} itens encontrados • {1} podem ser liberados",
            "Nada para limpar.",
            "Local",
            "Itens",
            "Tamanho",
            "Caminho",
            "Confirmar limpeza",
            "{0} itens somando {1} serão movidos para a Lixeira, de onde você pode restaurá-los. Deseja continuar?",
            "{0} movidos para a Lixeira. {1} ignorados por estarem em uso ou protegidos.",
            "Tudo vai para a Lixeira, então dá para desfazer.",
            "Marque os locais que deseja limpar.",
            "Arquivos temporários (usuário)",
            "Arquivos temporários (Windows)",
            "Cache de miniaturas",
            "Despejos de falhas",
            "Cache de navegadores",
            "Vídeo",
            "Imagens",
            "Áudio",
            "Compactados",
            "Código",
            "Documentos",
            "Sistema",
            "Outros",
            "UNIDADES",
            "TIPOS DE ARQUIVO",
            "{0} arquivos · {1} pastas · varredura {2}",
            "{0} arquivos/s",
            "{0} usados de {1} · {2} livres",
            "Não apague manualmente",
            "Aplicativos",
            "Processos em segundo plano",
            "Clique numa linha para escolher arquivo por arquivo.",
            "{0} de {1} selecionados · {2}",
            "Mover para a Lixeira",
            "Mover para a Lixeira",
            "\"{0}\" ({1}) será movido para a Lixeira, de onde você pode restaurá-lo.\n\nDeseja continuar?",
            "Atenção: este é um arquivo do sistema Windows. Removê-lo pode deixar o sistema instável ou impedir a inicialização.",
            "Não foi possível mover para a Lixeira. O arquivo pode estar em uso ou protegido.",
            "Pesquisar o nome do processo",
            "é vírus ou malware ou processo legítimo do Windows",
            "Origem",
            "Windows",
            "Opções",
            "Idioma",
            "Tema",
            "Ferramenta de busca",
            "Fechar",
            "Automático (do sistema)",
            "Sistema",
            "Claro",
            "Escuro",
            "PASTAS",
            "Possíveis sobras de aplicativos",
            "Caches conhecidos de aplicativos",
            "Limpeza cancelada: um ou mais itens estão abertos, em uso ou mudaram desde a análise. Nenhum item foi enviado à Lixeira."
        ],
        Language.Spanish =>
        [
            "DiskLit — Analizador de espacio en disco",
            "Descubra qué está ocupando su disco",
            "Seleccione un disco. El análisis solo lee los archivos y no elimina nada.",
            "Analizar",
            "Detener",
            "Filtrar entre los archivos más grandes...",
            "Todas las carpetas",
            "Nombre",
            "Tamaño",
            "Ubicación",
            "Modificado",
            "Abrir ubicación",
            "Copiar ruta",
            "Listo",
            "Analizando en segundo plano; puede detenerlo en cualquier momento.",
            "Análisis interrumpido.",
            "No se pudo completar: ",
            "SSD/NVMe",
            "modo secuencial",
            "(raíz)",
            "No se pudo abrir",
            "No se pudo copiar",
            "{0} archivos • {1} leídos • {2} inaccesibles • {3}",
            "{0} archivos • {1} • {2} • {3} • {4} inaccesibles",
            "Listo. Mostrando los {0} archivos más grandes; el filtro busca solo entre ellos. Haga doble clic para abrir la ubicación.",
            "{0}  {1}  •  {2} de {3}",
            "—",
            "Tema: sistema",
            "Tema: claro",
            "Tema: oscuro",
            "Archivos",
            "Activos",
            "Limpieza",
            "Archivo del sistema Windows",
            "No lo elimine manualmente. Windows vuelve a crearlo, y quitarlo a mano puede dejar el sistema inestable o impedir que arranque.",
            "Este elemento pertenece a Windows y lo administra el propio sistema.",
            "Guarda el contenido de la memoria RAM cuando el equipo hiberna, por eso ocupa aproximadamente el tamaño de la memoria instalada. El Inicio rápido también lo usa. Para liberar el espacio, desactive la hibernación con \"powercfg /h off\" en un símbolo del sistema como administrador.",
            "Es la memoria virtual. Windows mueve aquí las páginas menos usadas cuando la RAM se llena, así que su tamaño depende de su RAM y de su carga de trabajo. Ajústelo en Propiedades del sistema > Opciones avanzadas > Rendimiento > Memoria virtual.",
            "Memoria virtual reservada para aplicaciones de Microsoft Store, administrada junto con el archivo de paginación.",
            "Es una instantánea de la memoria escrita tras un pantallazo azul, conservada para diagnóstico. Puede llegar al tamaño de su RAM. Elimínelo con el Liberador de espacio en disco, en la opción de volcados de memoria de errores del sistema.",
            "Pequeño registro que Windows escribe durante el apagado y al manejar fallos.",
            "Es la instalación anterior de Windows, conservada para poder revertir una actualización. Windows la elimina sola al cabo de unos diez días. Si necesita el espacio antes, use el Sensor de almacenamiento o el Liberador de espacio en disco.",
            "Es el almacén de componentes, con todas las versiones de archivos que Windows necesita para actualizar y reparar. El espacio real es mucho menor de lo que aparenta, porque la mayoría de las entradas son vínculos duros a archivos que ya existen en otro sitio.",
            "Guarda puntos de restauración, datos de indexación y metadatos del volumen. Controle su tamaño desde Protección del sistema.",
            "Son los archivos que eliminó, todavía recuperables hasta que vacíe la Papelera.",
            "Guarda datos de instalación que Windows usa para reparar, actualizar y desinstalar programas. Borrarlo rompe esas operaciones y no se puede recrear.",
            "Contiene puntos de restauración del sistema. Ajuste el espacio reservado en Protección del sistema en lugar de borrar los archivos.",
            "Vista en vivo de lo que se está ejecutando. Solo lectura: DiskLit no finaliza procesos.",
            "Actualizar",
            "Proceso",
            "PID",
            "CPU",
            "Memoria",
            "Ejecutable",
            "{0} procesos • {1} de memoria en uso",
            "No se pudo leer la lista de procesos.",
            "Cachés conocidos y posibles restos. Revise el contenido: los candidatos profundos quedan sin marcar.",
            "Buscar",
            "Mover a la Papelera",
            "Buscando...",
            "{0} elementos encontrados • {1} se pueden liberar",
            "Nada que limpiar.",
            "Ubicación",
            "Elementos",
            "Tamaño",
            "Ruta",
            "Confirmar limpieza",
            "{0} elementos que suman {1} se moverán a la Papelera, desde donde puede restaurarlos. ¿Desea continuar?",
            "{0} movidos a la Papelera. {1} omitidos por estar en uso o protegidos.",
            "Todo va a la Papelera, así que se puede deshacer.",
            "Marque las ubicaciones que desea limpiar.",
            "Archivos temporales (usuario)",
            "Archivos temporales (Windows)",
            "Caché de miniaturas",
            "Volcados de fallos",
            "Caché de navegadores",
            "Vídeo",
            "Imágenes",
            "Audio",
            "Comprimidos",
            "Código",
            "Documentos",
            "Sistema",
            "Otros",
            "UNIDADES",
            "TIPOS DE ARCHIVO",
            "{0} archivos · {1} carpetas · análisis {2}",
            "{0} archivos/s",
            "{0} usados de {1} · {2} libres",
            "No lo elimine manualmente",
            "Aplicaciones",
            "Procesos en segundo plano",
            "Haga clic en una fila para elegir archivo por archivo.",
            "{0} de {1} seleccionados · {2}",
            "Mover a la Papelera",
            "Mover a la Papelera",
            "\"{0}\" ({1}) se moverá a la Papelera, desde donde puede restaurarlo.\n\n¿Desea continuar?",
            "Atención: este es un archivo del sistema Windows. Quitarlo puede dejar el sistema inestable o impedir que arranque.",
            "No se pudo mover a la Papelera. El archivo puede estar en uso o protegido.",
            "Buscar el nombre del proceso",
            "es virus o malware o proceso legítimo de Windows",
            "Origen",
            "Windows",
            "Opciones",
            "Idioma",
            "Tema",
            "Buscador",
            "Cerrar",
            "Automático (del sistema)",
            "Sistema",
            "Claro",
            "Oscuro",
            "CARPETAS",
            "Posibles restos de aplicaciones",
            "Cachés conocidos de aplicaciones",
            "Limpieza cancelada: uno o más elementos están abiertos, en uso o cambiaron desde el análisis. No se envió ningún elemento a la Papelera."
        ],
        Language.Russian =>
        [
            "DiskLit — Анализатор дискового пространства",
            "Узнайте, что занимает место на диске",
            "Выберите диск. Анализ только читает файлы и ничего не удаляет.",
            "Анализировать",
            "Остановить",
            "Поиск среди крупнейших файлов...",
            "Все папки",
            "Имя",
            "Размер",
            "Расположение",
            "Изменён",
            "Открыть расположение файла",
            "Копировать путь",
            "Готово",
            "Анализ выполняется в фоне; его можно остановить в любой момент.",
            "Анализ прерван.",
            "Не удалось завершить: ",
            "SSD/NVMe",
            "последовательный режим",
            "(корень)",
            "Не удалось открыть",
            "Не удалось скопировать",
            "{0} файлов • {1} прочитано • {2} недоступно • {3}",
            "{0} файлов • {1} • {2} • {3} • {4} недоступно",
            "Готово. Показаны {0} крупнейших файлов; поиск работает только по ним. Дважды щёлкните, чтобы открыть расположение.",
            "{0}  {1}  •  {2} из {3}",
            "—",
            "Тема: системная",
            "Тема: светлая",
            "Тема: тёмная",
            "Файлы",
            "Активные",
            "Очистка",
            "Системный файл Windows",
            "Не удаляйте вручную. Windows создаст файл заново, а удаление вручную может нарушить работу системы или помешать загрузке.",
            "Этот объект принадлежит Windows и управляется самой системой.",
            "Хранит содержимое оперативной памяти при переходе компьютера в режим гибернации, поэтому занимает примерно столько же, сколько установлено памяти. Быстрый запуск тоже использует этот файл. Чтобы освободить место, отключите гибернацию командой \"powercfg /h off\" в командной строке от имени администратора.",
            "Это виртуальная память. Когда оперативной памяти не хватает, Windows переносит сюда наименее используемые страницы, поэтому размер зависит от объёма ОЗУ и нагрузки. Настраивается в разделе Свойства системы > Дополнительно > Быстродействие > Виртуальная память.",
            "Виртуальная память для приложений Microsoft Store, управляется вместе с файлом подкачки.",
            "Снимок памяти, записанный после синего экрана и сохранённый для диагностики. Может достигать объёма вашей оперативной памяти. Удаляется через «Очистку диска», пункт с дампами памяти системных ошибок.",
            "Небольшой журнал, который Windows пишет при завершении работы и обработке сбоев.",
            "Это предыдущая установка Windows, сохранённая для отката обновления. Windows удаляет её сама примерно через десять дней. Если место нужно раньше, используйте «Контроль памяти» или «Очистку диска».",
            "Это хранилище компонентов со всеми версиями файлов, необходимых Windows для обновления и восстановления. Реально занимает гораздо меньше, чем кажется, потому что большинство записей — жёсткие ссылки на уже существующие файлы.",
            "Хранит точки восстановления, данные индексации и метаданные тома. Размер настраивается в «Защите системы».",
            "Это удалённые вами файлы, их ещё можно восстановить, пока корзина не очищена.",
            "Хранит данные установки, которые Windows использует для восстановления, обновления и удаления программ. Удаление ломает эти операции без возможности восстановления.",
            "Содержит точки восстановления системы. Настройте отведённое место в «Защите системы», вместо того чтобы удалять файлы.",
            "Живой список запущенного. Только чтение: DiskLit не завершает процессы.",
            "Обновить",
            "Процесс",
            "PID",
            "ЦП",
            "Память",
            "Исполняемый файл",
            "{0} процессов • {1} памяти используется",
            "Не удалось получить список процессов.",
            "Известные кэши и возможные остатки. Проверьте содержимое: кандидаты глубокой очистки не отмечены.",
            "Найти",
            "Переместить в корзину",
            "Поиск...",
            "Найдено объектов: {0} • можно освободить {1}",
            "Очищать нечего.",
            "Расположение",
            "Объектов",
            "Размер",
            "Путь",
            "Подтвердите очистку",
            "{0} объектов общим объёмом {1} будут перемещены в корзину, откуда их можно восстановить. Продолжить?",
            "Перемещено в корзину: {0}. Пропущено: {1} (используются или защищены).",
            "Всё отправляется в корзину, поэтому действие можно отменить.",
            "Отметьте расположения, которые нужно очистить.",
            "Временные файлы (пользователь)",
            "Временные файлы (Windows)",
            "Кэш эскизов",
            "Дампы сбоев",
            "Кэш браузеров",
            "Видео",
            "Изображения",
            "Аудио",
            "Архивы",
            "Код",
            "Документы",
            "Система",
            "Прочее",
            "ДИСКИ",
            "ТИПЫ ФАЙЛОВ",
            "{0} файлов · {1} папок · сканирование {2}",
            "{0} файлов/с",
            "{0} занято из {1} · {2} свободно",
            "Не удаляйте вручную",
            "Приложения",
            "Фоновые процессы",
            "Щёлкните строку, чтобы выбрать отдельные файлы.",
            "Выбрано {0} из {1} · {2}",
            "Переместить в корзину",
            "Переместить в корзину",
            "\"{0}\" ({1}) будет перемещён в корзину, откуда его можно восстановить.\n\nПродолжить?",
            "Внимание: это системный файл Windows. Его удаление может нарушить работу системы или помешать загрузке.",
            "Не удалось переместить в корзину. Файл может использоваться или быть защищён.",
            "Найти имя процесса",
            "это вирус или вредоносная программа malware или системный процесс Windows",
            "Источник",
            "Windows",
            "Параметры",
            "Язык",
            "Тема",
            "Поисковик",
            "Закрыть",
            "Автоматически (как в системе)",
            "Системная",
            "Светлая",
            "Тёмная",
            "ПАПКИ",
            "Возможные остатки приложений",
            "Известные кэши приложений",
            "Очистка отменена: один или несколько элементов открыты, используются или изменились после анализа. Ничего не перемещено в корзину."
        ],
        _ =>
        [
            "DiskLit — Disk Space Analyzer",
            "See what is taking up your disk",
            "Select a drive. The scan only reads files and deletes nothing.",
            "Analyze",
            "Stop",
            "Filter among the largest files...",
            "All folders",
            "Name",
            "Size",
            "Location",
            "Modified",
            "Open file location",
            "Copy path",
            "Ready",
            "Scanning in the background; you can stop at any time.",
            "Scan stopped.",
            "Could not finish: ",
            "SSD/NVMe",
            "sequential mode",
            "(root)",
            "Could not open",
            "Could not copy",
            "{0} files • {1} read • {2} inaccessible • {3}",
            "{0} files • {1} • {2} • {3} • {4} inaccessible",
            "Done. Showing the {0} largest files; the filter searches only among them. Double-click to open the location.",
            "{0}  {1}  •  {2} of {3}",
            "—",
            "Theme: system",
            "Theme: light",
            "Theme: dark",
            "Files",
            "Active",
            "Cleanup",
            "Windows system file",
            "Do not delete it manually. Windows recreates it, and removing it by hand can leave the system unstable or unable to boot.",
            "This item belongs to Windows and is managed by the system itself.",
            "Holds the contents of your RAM while the PC hibernates, so it is roughly the size of your installed memory. Fast Startup uses it too. To reclaim the space, turn hibernation off with \"powercfg /h off\" in an elevated prompt.",
            "This is virtual memory. Windows moves the least used memory pages here when RAM fills up, so its size tracks your RAM and your workload. Adjust it under System Properties > Advanced > Performance > Virtual memory.",
            "Virtual memory reserved for Microsoft Store apps, managed together with the page file.",
            "A snapshot of memory written after a blue screen and kept for diagnosis. It can grow to the size of your RAM. Remove it with Disk Cleanup, under system error memory dumps.",
            "A small log Windows writes during shutdown and crash handling.",
            "Your previous Windows installation, kept so you can roll back an upgrade. Windows deletes it on its own after about ten days. If you need the space sooner, use Storage Sense or Disk Cleanup.",
            "The component store, holding every version of the files Windows needs to update and repair itself. It uses far less space than it appears to, because most entries are hard links to files that already exist elsewhere.",
            "Holds restore points, indexing data and volume metadata. Control its size through System Protection.",
            "Files you deleted, still recoverable until the Recycle Bin is emptied.",
            "Cached installer data Windows uses to repair, update and uninstall programs. Deleting it breaks those operations and cannot be undone.",
            "Contains system restore points. Adjust the reserved space under System Protection rather than deleting the files.",
            "A live view of what is running. Read-only: DiskLit does not end processes.",
            "Refresh",
            "Process",
            "PID",
            "CPU",
            "Memory",
            "Executable",
            "{0} processes • {1} memory in use",
            "Could not read the process list.",
            "Known caches and possible leftovers. Review the contents: deep candidates are unchecked.",
            "Find items",
            "Move to Recycle Bin",
            "Searching...",
            "{0} items found • {1} can be freed",
            "Nothing to clean.",
            "Location",
            "Items",
            "Size",
            "Path",
            "Confirm cleanup",
            "{0} items totalling {1} will be moved to the Recycle Bin, where you can restore them. Continue?",
            "{0} moved to the Recycle Bin. {1} skipped because they are in use or protected.",
            "Everything goes to the Recycle Bin, so you can undo it.",
            "Tick the locations you want to clean.",
            "Temporary files (user)",
            "Temporary files (Windows)",
            "Thumbnail cache",
            "Crash dumps",
            "Browser caches",
            "Video",
            "Images",
            "Audio",
            "Archives",
            "Code",
            "Documents",
            "System",
            "Other",
            "DRIVES",
            "FILE TYPES",
            "{0} files · {1} folders · scan {2}",
            "{0} files/s",
            "{0} used of {1} · {2} free",
            "Do not delete manually",
            "Apps",
            "Background processes",
            "Click a row to choose file by file.",
            "{0} of {1} selected · {2}",
            "Move to Recycle Bin",
            "Move to Recycle Bin",
            "\"{0}\" ({1}) will be moved to the Recycle Bin, where you can restore it.\n\nContinue?",
            "Warning: this is a Windows system file. Removing it can leave the system unstable or unable to boot.",
            "Could not move it to the Recycle Bin. The file may be in use or protected.",
            "Search the process name",
            "virus or malware or legitimate Windows process",
            "Source",
            "Windows",
            "Options",
            "Language",
            "Theme",
            "Search engine",
            "Close",
            "Automatic (system)",
            "System",
            "Light",
            "Dark",
            "FOLDERS",
            "Possible application leftovers",
            "Known application caches",
            "Cleanup cancelled: one or more items are open, in use, or changed since the scan. Nothing was sent to the Recycle Bin."
        ]
    };
}
